version: '3.8'
services:
  akka-node-1:
    build: .
    container_name: akka-node-1
    ports:
      - "8080:8080"
      - "2551:2551"
    environment:
      AKKA_REMOTE_HOSTNAME: akka-node-1
      AKKA_REMOTE_PORT: 2551
    networks:
      - akka-net

  akka-node-2:
    build: .
    container_name: akka-node-2
    ports:
      - "8081:8080"
      - "2552:2552"
    environment:
      AKKA_REMOTE_HOSTNAME: akka-node-2
      AKKA_REMOTE_PORT: 2552
    networks:
      - akka-net

  akka-node-3:
    build: .
    container_name: akka-node-3
    ports:
      - "8082:8080"
      - "2553:2553"
    environment:
      AKKA_REMOTE_HOSTNAME: akka-node-3
      AKKA_REMOTE_PORT: 2553
    networks:
      - akka-net

  load-balancer:
    image: nginx:latest
    container_name: akka-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - akka-net

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chem_query_db
      POSTGRES_USER: chem_user
      POSTGRES_PASSWORD: chem_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - akka-net

volumes:
  postgres_data:

networks:
  akka-net:
    driver: bridge