server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: chem-query-platform-demo
  datasource:
    url: jdbc:postgresql://db:5432/chem_query_db
    username: chem_user
    password: chem_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

elasticsearch:
  hosts:
    - http://localhost:9200
  username: elastic
  password: elastic

indigo:
  pool:
    maximum-pool-size: 500
    timeoutInSeconds: 30
  inchi:
    pool:
      maximum-pool-size: 100
      timeoutInSeconds: 30

akka:
  actor:
    provider: cluster
    serializers:
      jackson-cbor: "akka.serialization.jackson.JacksonCborSerializer"
    serialization-bindings:
      "com.quantori.cqp.core.task.actor.StreamTaskActor$Command": jackson-cbor
      "com.quantori.cqp.core.task.model.StreamTaskStatus": jackson-cbor
      "com.quantori.cqp.core.task.model.StreamTaskDetails": jackson-cbor
      "com.quantori.cqp.core.task.model.StreamTaskResult": jackson-cbor
      "com.quantori.cqp.core.task.model.StreamTaskProcessingException": jackson-cbor
  remote:
    artery:
      canonical:
        hostname: 127.0.0.1
        port: 25520
  cluster:
    seed-nodes:
      - akka://ClusterSystem@127.0.0.1:2551
      - akka://ClusterSystem@127.0.0.1:2552
      - akka://ClusterSystem@127.0.0.1:2553
    downing-provider-class: akka.cluster.sbr.SplitBrainResolverProvider
    auto-down-unreachable-after: 10s

app:
  search:
    actors:
      max: 100
  cluster:
    hostname: localhost
    port: 2551
    nodes:
      - 127.0.0.1:2551
      - 127.0.0.1:2552
      - 127.0.0.1:2553
